apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: GameServerTemplateDeployment #This will be modified during creation to "templatename-Deployment-"
  labels: #These Labels are used to attribute objects to individual Templates
    gameserver: cuberite #Adapt
    deploymentType: gameserver #This Label must not be changed
    deploymentUUID: "12345" #Generated before deployment to cluster to uniquely identify deployments
    name: GameServerTemplateName #This Label is used to store the User chosen Name of a deployed Gameserver
spec:
  selector:
    matchLabels: #This Section is equivalent to the template Labels below and will be overwritten on deployment
      gameserver: cuberite #Overwritten
      deploymentType: gameserver #Overwritten
      deploymentUUID: "12345" #Overwritten
  replicas: 1
  template:
    metadata:
      labels: #This Section contains the Labels that will be deployed
        gameserver: cuberite #Adapt
        deploymentType: gameserver #This Label must not be changed
        deploymentUUID: "12345" #Generated before deployment to cluster to uniquely identify deployments
    spec:
      initContainers:
        - name: cuberite-init
          image: dregistry.gahr.dev/cuberite-init:latest
          resources:
            limits:
              cpu: 1000m
              memory: 50Mi
          envFrom:
            - configMapRef:
                name: GameServerTemplateConfigMap #This Name will be overwritten with the previously created ConfigMap
                optional: false
          volumeMounts:
            - name: volume1
              mountPath: /volume
      containers:
        - name: cuberite-server
          image: dregistry.gahr.dev/cuberite-gs:latest
          resources:
            limits:
              cpu: 1000m
              memory: 1G
          tty: true
          envFrom:
            - configMapRef:
                name: GameServerTemplateConfigMap #This Name will be overwritten with the previously created ConfigMap
                optional: false
          volumeMounts:
            - name: volume1
              subPath: settings.ini
              mountPath: /cuberite/settings.ini
            - name: volume1
              subPath: webadmin.ini
              mountPath: /cuberite/webadmin.ini
            - name: volume1
              subPath: world/
              mountPath: /cuberite/world/
            - name: volume1
              subPath: world_nether/
              mountPath: /cuberite/world_nether/
            - name: volume1
              subPath: world_the_end/
              mountPath: /cuberite/world_the_end/
            - name: volume1
              subPath: logs/
              mountPath: /cuberite/logs/
            - name: volume1
              subPath: players/
              mountPath: /cuberite/players/
            - name: volume1
              subPath: data/MojangAPI.sqlite
              mountPath: /cuberite/MojangAPI.sqlite
            - name: volume1
              subPath: data/Ranks.sqlite
              mountPath: /cuberite/Ranks.sqlite
            - name: volume1
              subPath: data/banlist.sqlite
              mountPath: /cuberite/banlist.sqlite
            - name: volume1
              subPath: data/whitelist.sqlite
              mountPath: /cuberite/whitelist.sqlite
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 8888
              protocol: TCP
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: GameServerTemplatePersistentVolumeClaim #This Name will be overwritten with the previously created PVC
      securityContext:
        fsGroup: 1000