apiVersion: v1
kind: Service
metadata:
  generateName: GameServerTemplateService #This will be modified during creation to "templatename-Service-"
  labels: #These Labels are used to attribute objects to individual Templates
    gameserver: cuberite #Adapt
    deploymentType: gameserver #This Label must not be changed
    deploymentUUID: "12345" #Generated before deployment to cluster to uniquely identify deployments
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: minecraft
      port: 25565
      #targetPort: 25565
    - protocol: TCP
      name: cuberite-webadmin
      port: 8888
      #targetPort: 8888
  selector: #This section is taken from Deployment.Spec.Template.Metadata.Labels
    gameserver: cuberite #Adapt
    deployment: gameserver #This Label must not be changed
    deploymentUUID: "12345" #Generated before deployment to cluster to uniquely identify deployments