apiVersion: v1
kind: Service
metadata:
  name: cuberite-service
  namespace: user0 #Dynamic
  labels:
    gameserver: cuberite
    deployment: gameserver
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    gameserver: cuberite
    deployment: gameserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuberite-deployment
spec:
  selector:
    matchLabels:
      gameserver: cuberite
      deployment: gameserver
  replicas: 1
  template:
    metadata:
      namespace: user0 #Dynamic
      labels:
        gameserver: cuberite
        deployment: gameserver
    spec:
      containers:
        - name: cuberite-server
          image: dregistry.gahr.dev/cuberite:latest
          resources:
            limits:
              cpu: 1000m
              memory: 1G
          envFrom:
            - configMapRef:
                name: cuberite-config
                optional: false
          ports:
            - containerPort: 80
              protocol: TCP
---
#kubectl create configmap C --from-env-file=servers\cuberite\default.env
apiVersion: v1
kind: ConfigMap
metadata:
  name: cuberite-config
  namespace: default
data:
  DESCRIPTION: Cuberite Server deployed by Gamebase
  PLAYERCOUNT: "11"
  SERVER_PORT: "25565"
  WEBADMIN_ENABLED: "1"
  WEBADMIN_PORT: "8888"